"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
    {
        "source": "src/main/resources/assets/sit-oth3r/lang/en_US.json",
        "translation": "src/main/resources/assets/sit-oth3r/lang/%locale_with_underscore%.json",
    }
]