# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
# inclusive
min_minecraft_version=26.1
# exclusive
max_minecraft_version=26.2
# tested and working versions for mod posting
minecraft_versions=26.1,26.1.1,26.1.2

minecraft_version=26.1.2
loader_version=0.18.5
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.2.6.0+26.1.1
maven_group=one.oth3r
file_name=sit!

# Dependencies
fabric_api_version=0.145.4+26.1.2
otterlib_version=0.3.0.0+26.1.1-fabric
otterlib_max_version=0.4.0.0+26.1.1-fabric

modmenu_version=18.0.0-alpha.6
devauth_version=1.2.2
